sudo: false

language: ruby
rvm:
  - 2.0.0

script:
  - npm install -g bower
  - bower install
  - jekyll build

after_success:
  - ./deploy.sh

# The encryption label is the unique key used in the environment
# variables set up when calling `travis encrypt-file` on the SSH key
env:
  global:
    - ENCRYPTION_LABEL="8417706c747f"
    - GIT_NAME="Travis CI"
    - GIT_EMAIL="sonrisesoftware@gmail.com"
    - SOURCE_BRANCH="source"

branches:
  except:
    - master

notifications:
  slack: papyros:KBYIhW6PbotRKo3MO1CZ15aF
