# Site settings
title: Papyros
email: mspencer@sonrisesoftware.com
description: > # this means to ignore newlines until "baseurl:"
  Papyros is a modern operating system which adheres to Google's
  Material Design guidelines and is based on Arch Linux.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://papyros.io" # the base hostname & protocol for your site
github_username:  papyros

# Build settings
markdown: kramdown

# Google Analytics
google_analytics_tracking_id: UA-47662876-2

# Disqus comments
disqus_short_name: quartzos
disqus_show_comment_count: true
